---
language: python
services: docker

addons:
  apt:
    packages:
      - python3-pip

env:
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"

install:
  - pip install -r requirements.txt

script:
  - molecule test --destroy never
  - molecule test --scenario-name ultrastack

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
